### ISSUE TITLE
instagib doesn't register any hits on opponents

### ISSUE THREAD

**Issue by ciscon** [molgrum/cspree#8] opened 2017-03-31 21:26 UTC
this is happening on my server which is running on cspree from git, ftesv from git (default make options), on armv71

**Comment by molgrum** [comment] 2017-04-04 06:23
Looking into this. The problem is probably that gmapn_impact() does not change the opponents health (to -100) because of a faulty condition. Since bullets are fired and no blood is drawn on hit.

**Comment by molgrum** [comment] 2017-04-05 16:47
@ciscon should be fixed now!

**Closed as completed** 2017-04-13 17:40 UTC
